/* ------------------------------- CREATE SEQUENCES ------------------------------ */

CREATE SEQUENCE GS_USUARIO_SEQ START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE GS_VEICULO_SEQ START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE GS_POSTO_CARREGAMENTO_SEQ START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE GS_PONTO_CARREGAMENTO_SEQ START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE GS_RESERVA_SEQ START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE GS_HISTORICO_CARREGAMENTO_SEQ START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE GS_AVALIACAO_SEQ START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE GS_VIAGEM_SEQ START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE GS_PONTO_PARADA_SEQ START WITH 1 INCREMENT BY 1;

/* ------------------------------- CREATE TABLES ------------------------------ */

CREATE TABLE GS_USUARIO (
    USUARIO_ID NUMBER DEFAULT GS_USUARIO_SEQ.NEXTVAL PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    SENHA VARCHAR2(100) NOT NULL,
    IMG_PERFIL BLOB,
    DATA_CRIACAO DATE DEFAULT SYSDATE,
    ULTIMA_LOCALIZACAO VARCHAR2(50)
);

CREATE TABLE GS_VEICULO (
    VEICULO_ID NUMBER DEFAULT GS_VEICULO_SEQ.NEXTVAL PRIMARY KEY,
    USUARIO_ID NUMBER NOT NULL,
    MARCA VARCHAR2(50) NOT NULL,
    MODELO VARCHAR2(50) NOT NULL,
    ANO NUMBER(4),
    AUTONOMIA NUMBER,
    TIPO_CONECTOR VARCHAR2(50),
    CONSTRAINT FK_USUARIO_VEICULO FOREIGN KEY (USUARIO_ID) REFERENCES GS_USUARIO(USUARIO_ID)
);

CREATE TABLE GS_POSTO_CARREGAMENTO (
    POSTO_ID NUMBER DEFAULT GS_POSTO_CARREGAMENTO_SEQ.NEXTVAL PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    LATITUDE NUMBER(10, 6),
    LONGITUDE NUMBER(10, 6),
    ENDERECO VARCHAR2(200),
    HORARIO_FUNCIONAMENTO VARCHAR2(100),
    FORMAS_PAGAMENTO VARCHAR2(100),
    AVALIACAO_MEDIA NUMBER(3, 2)
);

CREATE TABLE GS_PONTO_CARREGAMENTO (
    PONTO_ID NUMBER DEFAULT GS_PONTO_CARREGAMENTO_SEQ.NEXTVAL PRIMARY KEY,
    POSTO_ID NUMBER NOT NULL,
    TIPO_CONECTOR VARCHAR2(50),
    VELOCIDADE_CARREGAMENTO NUMBER,
    DISPONIBILIDADE VARCHAR2(20) CHECK (DISPONIBILIDADE IN ('disponível', 'ocupado')),
    RESERVAVEL CHAR(1) CHECK (RESERVAVEL IN ('S', 'N')),
    CONSTRAINT FK_POSTO_PONTO FOREIGN KEY (POSTO_ID) REFERENCES GS_POSTO_CARREGAMENTO(POSTO_ID)
);

CREATE TABLE GS_RESERVA (
    RESERVA_ID NUMBER DEFAULT GS_RESERVA_SEQ.NEXTVAL PRIMARY KEY,
    USUARIO_ID NUMBER NOT NULL,
    PONTO_ID NUMBER NOT NULL,
    DATA_RESERVA TIMESTAMP,
    STATUS VARCHAR2(20) CHECK (STATUS IN ('ativa', 'concluída', 'cancelada')),
    CONSTRAINT FK_USUARIO_RESERVA FOREIGN KEY (USUARIO_ID) REFERENCES GS_USUARIO(USUARIO_ID),
    CONSTRAINT FK_PONTO_RESERVA FOREIGN KEY (PONTO_ID) REFERENCES GS_PONTO_CARREGAMENTO(PONTO_ID)
);

CREATE TABLE GS_HISTORICO_CARREGAMENTO (
    HISTORICO_ID NUMBER DEFAULT GS_HISTORICO_CARREGAMENTO_SEQ.NEXTVAL PRIMARY KEY,
    USUARIO_ID NUMBER NOT NULL,
    PONTO_ID NUMBER NOT NULL,
    DATA_CARREGAMENTO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ENERGIA_CONSUMIDA NUMBER(5, 2),
    EMISSOES_EVITADAS NUMBER(5, 2),
    CONSTRAINT FK_USUARIO_HISTORICO FOREIGN KEY (USUARIO_ID) REFERENCES GS_USUARIO(USUARIO_ID),
    CONSTRAINT FK_PONTO_HISTORICO FOREIGN KEY (PONTO_ID) REFERENCES GS_PONTO_CARREGAMENTO(PONTO_ID)
);

CREATE TABLE GS_AVALIACAO (
    AVALIACAO_ID NUMBER DEFAULT GS_AVALIACAO_SEQ.NEXTVAL PRIMARY KEY,
    USUARIO_ID NUMBER NOT NULL,
    POSTO_ID NUMBER NOT NULL,
    NOTA NUMBER(1) CHECK (NOTA BETWEEN 1 AND 5),
    COMENTARIO VARCHAR2(500),
    DATA_AVALIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_USUARIO_AVALIACAO FOREIGN KEY (USUARIO_ID) REFERENCES GS_USUARIO(USUARIO_ID),
    CONSTRAINT FK_POSTO_AVALIACAO FOREIGN KEY (POSTO_ID) REFERENCES GS_POSTO_CARREGAMENTO(POSTO_ID)
);

CREATE TABLE GS_VIAGEM (
    VIAGEM_ID NUMBER DEFAULT GS_VIAGEM_SEQ.NEXTVAL PRIMARY KEY,
    USUARIO_ID NUMBER NOT NULL,
    ORIGEM VARCHAR2(50),
    DESTINO VARCHAR2(50),
    AUTONOMIA_RESTANTE NUMBER,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_USUARIO_VIAGEM FOREIGN KEY (USUARIO_ID) REFERENCES GS_USUARIO(USUARIO_ID)
);

CREATE TABLE GS_PONTO_PARADA (
    PONTO_PARADA_ID NUMBER DEFAULT GS_PONTO_PARADA_SEQ.NEXTVAL PRIMARY KEY,
    VIAGEM_ID NUMBER NOT NULL,
    PONTO_ID NUMBER NOT NULL,
    ORDEM NUMBER,
    CONSTRAINT FK_VIAGEM_PARADA FOREIGN KEY (VIAGEM_ID) REFERENCES GS_VIAGEM(VIAGEM_ID),
    CONSTRAINT FK_PONTO_PARADA FOREIGN KEY (PONTO_ID) REFERENCES GS_PONTO_CARREGAMENTO(PONTO_ID)
);

