
-- /* ------------------------------- DROP TABLES ------------------------------ */

-- IF OBJECT_ID('GS_USUARIO', 'U') IS NOT NULL DROP TABLE GS_USUARIO;
-- IF OBJECT_ID('GS_VEICULO', 'U') IS NOT NULL DROP TABLE GS_VEICULO;
-- IF OBJECT_ID('GS_POSTO_CARREGAMENTO', 'U') IS NOT NULL DROP TABLE GS_POSTO_CARREGAMENTO;
-- IF OBJECT_ID('GS_PONTO_CARREGAMENTO', 'U') IS NOT NULL DROP TABLE GS_PONTO_CARREGAMENTO;
-- IF OBJECT_ID('GS_RESERVA', 'U') IS NOT NULL DROP TABLE GS_RESERVA;
-- IF OBJECT_ID('GS_HISTORICO_CARREGAMENTO', 'U') IS NOT NULL DROP TABLE GS_HISTORICO_CARREGAMENTO;
-- IF OBJECT_ID('GS_AVALIACAO', 'U') IS NOT NULL DROP TABLE GS_AVALIACAO;
-- IF OBJECT_ID('GS_VIAGEM', 'U') IS NOT NULL DROP TABLE GS_VIAGEM;
-- IF OBJECT_ID('GS_PONTO_PARADA', 'U') IS NOT NULL DROP TABLE GS_PONTO_PARADA;

-- /* ------------------------------- DROP SEQUENCES ------------------------------ */

-- IF OBJECT_ID('GS_USUARIO_SEQ', 'SO') IS NOT NULL DROP SEQUENCE GS_USUARIO_SEQ;
-- IF OBJECT_ID('GS_VEICULO_SEQ', 'SO') IS NOT NULL DROP SEQUENCE GS_VEICULO_SEQ;
-- IF OBJECT_ID('GS_POSTO_CARREGAMENTO_SEQ', 'SO') IS NOT NULL DROP SEQUENCE GS_POSTO_CARREGAMENTO_SEQ;
-- IF OBJECT_ID('GS_PONTO_CARREGAMENTO_SEQ', 'SO') IS NOT NULL DROP SEQUENCE GS_PONTO_CARREGAMENTO_SEQ;
-- IF OBJECT_ID('GS_RESERVA_SEQ', 'SO') IS NOT NULL DROP SEQUENCE GS_RESERVA_SEQ;
-- IF OBJECT_ID('GS_HISTORICO_CARREGAMENTO_SEQ', 'SO') IS NOT NULL DROP SEQUENCE GS_HISTORICO_CARREGAMENTO_SEQ;
-- IF OBJECT_ID('GS_AVALIACAO_SEQ', 'SO') IS NOT NULL DROP SEQUENCE GS_AVALIACAO_SEQ;
-- IF OBJECT_ID('GS_VIAGEM_SEQ', 'SO') IS NOT NULL DROP SEQUENCE GS_VIAGEM_SEQ;
-- IF OBJECT_ID('GS_PONTO_PARADA_SEQ', 'SO') IS NOT NULL DROP SEQUENCE GS_PONTO_PARADA_SEQ;