-- CREATE SEQUENCE GS_USUARIO_SEQ START WITH 1 INCREMENT BY 1;

-- CREATE SEQUENCE GS_VEICULO_SEQ START WITH 1 INCREMENT BY 1;

-- CREATE SEQUENCE GS_POSTO_CARREGAMENTO_SEQ START WITH 1 INCREMENT BY 1;

-- CREATE SEQUENCE GS_PONTO_CARREGAMENTO_SEQ START WITH 1 INCREMENT BY 1;

-- CREATE SEQUENCE GS_RESERVA_SEQ START WITH 1 INCREMENT BY 1;

-- CREATE SEQUENCE GS_HISTORICO_CARREGAMENTO_SEQ START WITH 1 INCREMENT BY 1;

-- CREATE SEQUENCE GS_AVALIACAO_SEQ START WITH 1 INCREMENT BY 1;

-- CREATE SEQUENCE GS_VIAGEM_SEQ START WITH 1 INCREMENT BY 1;

-- CREATE SEQUENCE GS_PONTO_PARADA_SEQ START WITH 1 INCREMENT BY 1;

-- CREATE TABLE GS_USUARIO (
--     USUARIO_ID NUMBER PRIMARY KEY,
--     NOME VARCHAR2(100) NOT NULL,
--     EMAIL VARCHAR2(100) NOT NULL UNIQUE,
--     SENHA VARCHAR2(100) NOT NULL,
--     IMG_PERFIL BLOB,
--     DATA_CRIACAO DATE, --TIMESTAMP DEFAULT SYSTIMESTAMP / DEFAULT SYSDATE
--     ULTIMA_LOCALIZACAO VARCHAR2(50)
-- );

-- CREATE TABLE GS_VEICULO (
--     VEICULO_ID NUMBER PRIMARY KEY,
--     USUARIO_ID NUMBER NOT NULL,
--     MARCA VARCHAR2(50) NOT NULL,
--     MODELO VARCHAR2(50) NOT NULL,
--     ANO NUMBER(4),
--     AUTONOMIA NUMBER,
--     TIPO_CONECTOR VARCHAR2(50),
--     CONSTRAINT FK_USUARIO_VEICULO FOREIGN KEY (USUARIO_ID) REFERENCES GS_USUARIO(USUARIO_ID)
-- );

-- CREATE TABLE GS_POSTO_CARREGAMENTO (
--     POSTO_ID NUMBER PRIMARY KEY,
--     NOME VARCHAR2(100) NOT NULL,
--     LATITUDE NUMBER(10, 6),
--     LONGITUDE NUMBER(10, 6),
--     ENDERECO VARCHAR2(200),
--     HORARIO_FUNCIONAMENTO VARCHAR2(100),
--     FORMAS_PAGAMENTO VARCHAR2(100),
--     AVALIACAO_MEDIA NUMBER(3, 2)
-- );

-- CREATE TABLE GS_PONTO_CARREGAMENTO (
--     PONTO_ID NUMBER PRIMARY KEY,
--     POSTO_ID NUMBER NOT NULL,
--     TIPO_CONECTOR VARCHAR2(50),
--     VELOCIDADE_CARREGAMENTO NUMBER,
--     DISPONIBILIDADE VARCHAR2(20),
--     RESERVAVEL CHAR(1),
--     CONSTRAINT FK_POSTO_PONTO FOREIGN KEY (POSTO_ID) REFERENCES GS_POSTO_CARREGAMENTO(POSTO_ID)
-- );

-- CREATE TABLE GS_RESERVA (
--     RESERVA_ID NUMBER PRIMARY KEY,
--     USUARIO_ID NUMBER NOT NULL,
--     PONTO_ID NUMBER NOT NULL,
--     DATA_RESERVA TIMESTAMP,
--     STATUS VARCHAR2(20),
--     CONSTRAINT FK_USUARIO_RESERVA FOREIGN KEY (USUARIO_ID) REFERENCES GS_USUARIO(USUARIO_ID),
--     CONSTRAINT FK_PONTO_RESERVA FOREIGN KEY (PONTO_ID) REFERENCES GS_PONTO_CARREGAMENTO(PONTO_ID)
-- );

-- CREATE TABLE GS_HISTORICO_CARREGAMENTO (
--     HISTORICO_ID NUMBER PRIMARY KEY,
--     USUARIO_ID NUMBER NOT NULL,
--     PONTO_ID NUMBER NOT NULL,
--     DATA_CARREGAMENTO TIMESTAMP,
--     ENERGIA_CONSUMIDA NUMBER(5, 2),
--     EMISSOES_EVITADAS NUMBER(5, 2),
--     CONSTRAINT FK_USUARIO_HISTORICO FOREIGN KEY (USUARIO_ID) REFERENCES GS_USUARIO(USUARIO_ID),
--     CONSTRAINT FK_PONTO_HISTORICO FOREIGN KEY (PONTO_ID) REFERENCES GS_PONTO_CARREGAMENTO(PONTO_ID)
-- );

-- CREATE TABLE GS_AVALIACAO (
--     AVALIACAO_ID NUMBER PRIMARY KEY,
--     USUARIO_ID NUMBER NOT NULL,
--     POSTO_ID NUMBER NOT NULL,
--     NOTA NUMBER(1),
--     COMENTARIO VARCHAR2(500),
--     DATA_AVALIACAO TIMESTAMP,
--     CONSTRAINT FK_USUARIO_AVALIACAO FOREIGN KEY (USUARIO_ID) REFERENCES GS_USUARIO(USUARIO_ID),
--     CONSTRAINT FK_POSTO_AVALIACAO FOREIGN KEY (POSTO_ID) REFERENCES GS_POSTO_CARREGAMENTO(POSTO_ID)
-- );

-- CREATE TABLE GS_VIAGEM (
--     VIAGEM_ID NUMBER PRIMARY KEY,
--     USUARIO_ID NUMBER NOT NULL,
--     ORIGEM VARCHAR2(50),
--     DESTINO VARCHAR2(50),
--     AUTONOMIA_RESTANTE NUMBER,
--     DATA_CRIACAO TIMESTAMP,
--     CONSTRAINT FK_USUARIO_VIAGEM FOREIGN KEY (USUARIO_ID) REFERENCES GS_USUARIO(USUARIO_ID)
-- );

-- CREATE TABLE GS_PONTO_PARADA (
--     PONTO_PARADA_ID NUMBER PRIMARY KEY,
--     VIAGEM_ID NUMBER NOT NULL,
--     PONTO_ID NUMBER NOT NULL,
--     ORDEM NUMBER,
--     CONSTRAINT FK_VIAGEM_PARADA FOREIGN KEY (VIAGEM_ID) REFERENCES GS_VIAGEM(VIAGEM_ID),
--     CONSTRAINT FK_PONTO_PARADA FOREIGN KEY (PONTO_ID) REFERENCES GS_PONTO_CARREGAMENTO(PONTO_ID)
-- );

/* ------------------------------- DROP TABLES ------------------------------ */

IF OBJECT_ID('GS_USUARIO', 'U') IS NOT NULL DROP TABLE GS_USUARIO;

IF OBJECT_ID('GS_VEICULO', 'U') IS NOT NULL DROP TABLE GS_VEICULO;

IF OBJECT_ID('GS_POSTO_CARREGAMENTO', 'U') IS NOT NULL DROP TABLE GS_POSTO_CARREGAMENTO;

IF OBJECT_ID('GS_PONTO_CARREGAMENTO', 'U') IS NOT NULL DROP TABLE GS_PONTO_CARREGAMENTO;

IF OBJECT_ID('GS_RESERVA', 'U') IS NOT NULL DROP TABLE GS_RESERVA;

IF OBJECT_ID('GS_HISTORICO_CARREGAMENTO', 'U') IS NOT NULL DROP TABLE GS_HISTORICO_CARREGAMENTO;

IF OBJECT_ID('GS_AVALIACAO', 'U') IS NOT NULL DROP TABLE GS_AVALIACAO;

IF OBJECT_ID('GS_VIAGEM', 'U') IS NOT NULL DROP TABLE GS_VIAGEM;

IF OBJECT_ID('GS_PONTO_PARADA', 'U') IS NOT NULL DROP TABLE GS_PONTO_PARADA;

/* ------------------------------- DROP SEQUENCES ------------------------------ */

IF OBJECT_ID('GS_USUARIO_SEQ', 'SO') IS NOT NULL DROP SEQUENCE GS_USUARIO_SEQ;

IF OBJECT_ID('GS_VEICULO_SEQ', 'SO') IS NOT NULL DROP SEQUENCE GS_VEICULO_SEQ;

IF OBJECT_ID('GS_POSTO_CARREGAMENTO_SEQ', 'SO') IS NOT NULL DROP SEQUENCE GS_POSTO_CARREGAMENTO_SEQ;

IF OBJECT_ID('GS_PONTO_CARREGAMENTO_SEQ', 'SO') IS NOT NULL DROP SEQUENCE GS_PONTO_CARREGAMENTO_SEQ;

IF OBJECT_ID('GS_RESERVA_SEQ', 'SO') IS NOT NULL DROP SEQUENCE GS_RESERVA_SEQ;

IF OBJECT_ID('GS_HISTORICO_CARREGAMENTO_SEQ', 'SO') IS NOT NULL DROP SEQUENCE GS_HISTORICO_CARREGAMENTO_SEQ;

IF OBJECT_ID('GS_AVALIACAO_SEQ', 'SO') IS NOT NULL DROP SEQUENCE GS_AVALIACAO_SEQ;

IF OBJECT_ID('GS_VIAGEM_SEQ', 'SO') IS NOT NULL DROP SEQUENCE GS_VIAGEM_SEQ;

IF OBJECT_ID('GS_PONTO_PARADA_SEQ', 'SO') IS NOT NULL DROP SEQUENCE GS_PONTO_PARADA_SEQ;

/* ------------------------------- CREATE SEQUENCES ------------------------------ */

CREATE SEQUENCE GS_USUARIO_SEQ START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE GS_VEICULO_SEQ START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE GS_POSTO_CARREGAMENTO_SEQ START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE GS_PONTO_CARREGAMENTO_SEQ START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE GS_RESERVA_SEQ START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE GS_HISTORICO_CARREGAMENTO_SEQ START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE GS_AVALIACAO_SEQ START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE GS_VIAGEM_SEQ START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE GS_PONTO_PARADA_SEQ START WITH 1 INCREMENT BY 1;

/* ------------------------------- CREATE TABLES ------------------------------ */

CREATE TABLE GS_USUARIO (
    USUARIO_ID INT DEFAULT NEXT VALUE FOR GS_USUARIO_SEQ PRIMARY KEY,
    NOME NVARCHAR(100) NOT NULL,
    EMAIL NVARCHAR(100) NOT NULL UNIQUE,
    SENHA NVARCHAR(100) NOT NULL,
    IMG_PERFIL VARBINARY(MAX),
    DATA_CRIACAO DATETIME DEFAULT GETDATE(),
    ULTIMA_LOCALIZACAO NVARCHAR(50)
);

CREATE TABLE GS_VEICULO (
    VEICULO_ID INT DEFAULT NEXT VALUE FOR GS_VEICULO_SEQ PRIMARY KEY,
    USUARIO_ID INT NOT NULL,
    MARCA NVARCHAR(50) NOT NULL,
    MODELO NVARCHAR(50) NOT NULL,
    ANO INT,
    AUTONOMIA FLOAT,
    TIPO_CONECTOR NVARCHAR(50),
    CONSTRAINT FK_USUARIO_VEICULO FOREIGN KEY (USUARIO_ID) REFERENCES GS_USUARIO(USUARIO_ID)
);

CREATE TABLE GS_POSTO_CARREGAMENTO (
    POSTO_ID INT DEFAULT NEXT VALUE FOR GS_POSTO_CARREGAMENTO_SEQ PRIMARY KEY,
    NOME NVARCHAR(100) NOT NULL,
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    ENDERECO NVARCHAR(200),
    HORARIO_FUNCIONAMENTO NVARCHAR(100),
    FORMAS_PAGAMENTO NVARCHAR(100),
    AVALIACAO_MEDIA FLOAT
);

CREATE TABLE GS_PONTO_CARREGAMENTO (
    PONTO_ID INT DEFAULT NEXT VALUE FOR GS_PONTO_CARREGAMENTO_SEQ PRIMARY KEY,
    POSTO_ID INT NOT NULL,
    TIPO_CONECTOR NVARCHAR(50),
    VELOCIDADE_CARREGAMENTO FLOAT,
    DISPONIBILIDADE NVARCHAR(20) CHECK (DISPONIBILIDADE IN ('disponível', 'ocupado')),
    RESERVAVEL CHAR(1) CHECK (RESERVAVEL IN ('S', 'N')),
    CONSTRAINT FK_POSTO_PONTO FOREIGN KEY (POSTO_ID) REFERENCES GS_POSTO_CARREGAMENTO(POSTO_ID)
);

CREATE TABLE GS_RESERVA (
    RESERVA_ID INT DEFAULT NEXT VALUE FOR GS_RESERVA_SEQ PRIMARY KEY,
    USUARIO_ID INT NOT NULL,
    PONTO_ID INT NOT NULL,
    DATA_RESERVA DATETIME,
    STATUS NVARCHAR(20) CHECK (STATUS IN ('ativa', 'concluída', 'cancelada')),
    CONSTRAINT FK_USUARIO_RESERVA FOREIGN KEY (USUARIO_ID) REFERENCES GS_USUARIO(USUARIO_ID),
    CONSTRAINT FK_PONTO_RESERVA FOREIGN KEY (PONTO_ID) REFERENCES GS_PONTO_CARREGAMENTO(PONTO_ID)
);

CREATE TABLE GS_HISTORICO_CARREGAMENTO (
    HISTORICO_ID INT DEFAULT NEXT VALUE FOR GS_HISTORICO_CARREGAMENTO_SEQ PRIMARY KEY,
    USUARIO_ID INT NOT NULL,
    PONTO_ID INT NOT NULL,
    DATA_CARREGAMENTO DATETIME DEFAULT GETDATE(),
    ENERGIA_CONSUMIDA FLOAT,
    EMISSOES_EVITADAS FLOAT,
    CONSTRAINT FK_USUARIO_HISTORICO FOREIGN KEY (USUARIO_ID) REFERENCES GS_USUARIO(USUARIO_ID),
    CONSTRAINT FK_PONTO_HISTORICO FOREIGN KEY (PONTO_ID) REFERENCES GS_PONTO_CARREGAMENTO(PONTO_ID)
);

CREATE TABLE GS_AVALIACAO (
    AVALIACAO_ID INT DEFAULT NEXT VALUE FOR GS_AVALIACAO_SEQ PRIMARY KEY,
    USUARIO_ID INT NOT NULL,
    POSTO_ID INT NOT NULL,
    NOTA INT CHECK (NOTA BETWEEN 1 AND 5),
    COMENTARIO NVARCHAR(500),
    DATA_AVALIACAO DATETIME DEFAULT GETDATE(),
    CONSTRAINT FK_USUARIO_AVALIACAO FOREIGN KEY (USUARIO_ID) REFERENCES GS_USUARIO(USUARIO_ID),
    CONSTRAINT FK_POSTO_AVALIACAO FOREIGN KEY (POSTO_ID) REFERENCES GS_POSTO_CARREGAMENTO(POSTO_ID)
);

CREATE TABLE GS_VIAGEM (
    VIAGEM_ID INT DEFAULT NEXT VALUE FOR GS_VIAGEM_SEQ PRIMARY KEY,
    USUARIO_ID INT NOT NULL,
    ORIGEM NVARCHAR(50),
    DESTINO NVARCHAR(50),
    AUTONOMIA_RESTANTE FLOAT,
    DATA_CRIACAO DATETIME DEFAULT GETDATE(),
    CONSTRAINT FK_USUARIO_VIAGEM FOREIGN KEY (USUARIO_ID) REFERENCES GS_USUARIO(USUARIO_ID)
);

CREATE TABLE GS_PONTO_PARADA (
    PONTO_PARADA_ID INT DEFAULT NEXT VALUE FOR GS_PONTO_PARADA_SEQ PRIMARY KEY,
    VIAGEM_ID INT NOT NULL,
    PONTO_ID INT NOT NULL,
    ORDEM INT,
    CONSTRAINT FK_VIAGEM_PARADA FOREIGN KEY (VIAGEM_ID) REFERENCES GS_VIAGEM(VIAGEM_ID),
    CONSTRAINT FK_PONTO_PARADA FOREIGN KEY (PONTO_ID) REFERENCES GS_PONTO_CARREGAMENTO(PONTO_ID)
);