-- /* ------------------------------- DROP TABLES ------------------------------ */

-- IF OBJECT_ID('GS_PONTO_PARADA', 'U') IS NOT NULL DROP TABLE GS_PONTO_PARADA;
-- IF OBJECT_ID('GS_VIAGEM', 'U') IS NOT NULL DROP TABLE GS_VIAGEM;
-- IF OBJECT_ID('GS_AVALIACAO', 'U') IS NOT NULL DROP TABLE GS_AVALIACAO;
-- IF OBJECT_ID('GS_HISTORICO_CARREGAMENTO', 'U') IS NOT NULL DROP TABLE GS_HISTORICO_CARREGAMENTO;
-- IF OBJECT_ID('GS_RESERVA', 'U') IS NOT NULL DROP TABLE GS_RESERVA;
-- IF OBJECT_ID('GS_PONTO_CARREGAMENTO', 'U') IS NOT NULL DROP TABLE GS_PONTO_CARREGAMENTO;
-- IF OBJECT_ID('GS_POSTO_CARREGAMENTO', 'U') IS NOT NULL DROP TABLE GS_POSTO_CARREGAMENTO;
-- IF OBJECT_ID('GS_VEICULO', 'U') IS NOT NULL DROP TABLE GS_VEICULO;
-- IF OBJECT_ID('GS_USUARIO', 'U') IS NOT NULL DROP TABLE GS_USUARIO;

-- /* ------------------------------- DROP SEQUENCES ------------------------------ */

-- IF OBJECT_ID('GS_PONTO_PARADA_SEQ', 'SO') IS NOT NULL DROP SEQUENCE GS_PONTO_PARADA_SEQ;
-- IF OBJECT_ID('GS_VIAGEM_SEQ', 'SO') IS NOT NULL DROP SEQUENCE GS_VIAGEM_SEQ;
-- IF OBJECT_ID('GS_AVALIACAO_SEQ', 'SO') IS NOT NULL DROP SEQUENCE GS_AVALIACAO_SEQ;
-- IF OBJECT_ID('GS_HISTORICO_CARREGAMENTO_SEQ', 'SO') IS NOT NULL DROP SEQUENCE GS_HISTORICO_CARREGAMENTO_SEQ;
-- IF OBJECT_ID('GS_RESERVA_SEQ', 'SO') IS NOT NULL DROP SEQUENCE GS_RESERVA_SEQ;
-- IF OBJECT_ID('GS_PONTO_CARREGAMENTO_SEQ', 'SO') IS NOT NULL DROP SEQUENCE GS_PONTO_CARREGAMENTO_SEQ;
-- IF OBJECT_ID('GS_POSTO_CARREGAMENTO_SEQ', 'SO') IS NOT NULL DROP SEQUENCE GS_POSTO_CARREGAMENTO_SEQ;
-- IF OBJECT_ID('GS_VEICULO_SEQ', 'SO') IS NOT NULL DROP SEQUENCE GS_VEICULO_SEQ;
-- IF OBJECT_ID('GS_USUARIO_SEQ', 'SO') IS NOT NULL DROP SEQUENCE GS_USUARIO_SEQ;

/* ------------------------------- DROP TABLES ------------------------------ */

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'GS_PONTO_PARADA') AND type in (N'U')) DROP TABLE GS_PONTO_PARADA;
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'GS_VIAGEM') AND type in (N'U')) DROP TABLE GS_VIAGEM;
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'GS_AVALIACAO') AND type in (N'U')) DROP TABLE GS_AVALIACAO;
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'GS_HISTORICO_CARREGAMENTO') AND type in (N'U')) DROP TABLE GS_HISTORICO_CARREGAMENTO;
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'GS_RESERVA') AND type in (N'U')) DROP TABLE GS_RESERVA;
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'GS_PONTO_CARREGAMENTO') AND type in (N'U')) DROP TABLE GS_PONTO_CARREGAMENTO;
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'GS_POSTO_CARREGAMENTO') AND type in (N'U')) DROP TABLE GS_POSTO_CARREGAMENTO;
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'GS_VEICULO') AND type in (N'U')) DROP TABLE GS_VEICULO;
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'GS_USUARIO') AND type in (N'U')) DROP TABLE GS_USUARIO;

/* ------------------------------- DROP SEQUENCES ------------------------------ */

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'GS_PONTO_PARADA_SEQ') AND type in (N'SO')) DROP SEQUENCE GS_PONTO_PARADA_SEQ;
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'GS_VIAGEM_SEQ') AND type in (N'SO')) DROP SEQUENCE GS_VIAGEM_SEQ;
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'GS_AVALIACAO_SEQ') AND type in (N'SO')) DROP SEQUENCE GS_AVALIACAO_SEQ;
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'GS_HISTORICO_CARREGAMENTO_SEQ') AND type in (N'SO')) DROP SEQUENCE GS_HISTORICO_CARREGAMENTO_SEQ;
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'GS_RESERVA_SEQ') AND type in (N'SO')) DROP SEQUENCE GS_RESERVA_SEQ;
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'GS_PONTO_CARREGAMENTO_SEQ') AND type in (N'SO')) DROP SEQUENCE GS_PONTO_CARREGAMENTO_SEQ;
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'GS_POSTO_CARREGAMENTO_SEQ') AND type in (N'SO')) DROP SEQUENCE GS_POSTO_CARREGAMENTO_SEQ;
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'GS_VEICULO_SEQ') AND type in (N'SO')) DROP SEQUENCE GS_VEICULO_SEQ;
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'GS_USUARIO_SEQ') AND type in (N'SO')) DROP SEQUENCE GS_USUARIO_SEQ;

/* ------------------------------- CREATE SEQUENCES ------------------------------ */

CREATE SEQUENCE GS_USUARIO_SEQ START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE GS_VEICULO_SEQ START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE GS_POSTO_CARREGAMENTO_SEQ START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE GS_PONTO_CARREGAMENTO_SEQ START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE GS_RESERVA_SEQ START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE GS_HISTORICO_CARREGAMENTO_SEQ START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE GS_AVALIACAO_SEQ START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE GS_VIAGEM_SEQ START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE GS_PONTO_PARADA_SEQ START WITH 1 INCREMENT BY 1;

/* ------------------------------- CREATE TABLES ------------------------------ */

CREATE TABLE GS_USUARIO (
    USUARIO_ID INT DEFAULT NEXT VALUE FOR GS_USUARIO_SEQ PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    SENHA VARCHAR(100) NOT NULL,
    IMG_PERFIL VARCHAR(100),
    DATA_CRIACAO DATETIME2 DEFAULT GETDATE(),
    ULTIMA_LOCALIZACAO VARCHAR(50)
);

CREATE TABLE GS_VEICULO (
    VEICULO_ID INT DEFAULT NEXT VALUE FOR GS_VEICULO_SEQ PRIMARY KEY,
    USUARIO_ID INT NOT NULL,
    MARCA VARCHAR(50) NOT NULL,
    MODELO VARCHAR(50) NOT NULL,
    ANO INT,
    AUTONOMIA FLOAT,
    TIPO_CONECTOR VARCHAR(50),
    FOREIGN KEY (USUARIO_ID) REFERENCES GS_USUARIO(USUARIO_ID) ON DELETE CASCADE
);

CREATE TABLE GS_POSTO_CARREGAMENTO (
    POSTO_ID INT DEFAULT NEXT VALUE FOR GS_POSTO_CARREGAMENTO_SEQ PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    ENDERECO VARCHAR(200),
    HORARIO_FUNCIONAMENTO VARCHAR(100),
    FORMAS_PAGAMENTO VARCHAR(100),
    AVALIACAO_MEDIA FLOAT
);

CREATE TABLE GS_PONTO_CARREGAMENTO (
    PONTO_ID INT DEFAULT NEXT VALUE FOR GS_PONTO_CARREGAMENTO_SEQ PRIMARY KEY,
    POSTO_ID INT NOT NULL,
    TIPO_CONECTOR VARCHAR(50),
    VELOCIDADE_CARREGAMENTO FLOAT,
    DISPONIBILIDADE VARCHAR(20) CHECK (DISPONIBILIDADE IN ('disponível', 'ocupado')),
    RESERVAVEL CHAR(1) CHECK (RESERVAVEL IN ('S', 'N')),
    CONSTRAINT FK_POSTO_PONTO FOREIGN KEY (POSTO_ID) REFERENCES GS_POSTO_CARREGAMENTO(POSTO_ID) ON DELETE CASCADE
);

CREATE TABLE GS_RESERVA (
    RESERVA_ID INT DEFAULT NEXT VALUE FOR GS_RESERVA_SEQ PRIMARY KEY,
    USUARIO_ID INT NOT NULL,
    PONTO_ID INT NOT NULL,
    DATA_RESERVA DATETIME2 DEFAULT GETDATE(),
    STATUS VARCHAR(20) CHECK (STATUS IN ('ativa', 'concluída', 'cancelada')),
    CONSTRAINT FK_USUARIO_RESERVA FOREIGN KEY (USUARIO_ID) REFERENCES GS_USUARIO(USUARIO_ID) ON DELETE CASCADE,
    CONSTRAINT FK_PONTO_RESERVA FOREIGN KEY (PONTO_ID) REFERENCES GS_PONTO_CARREGAMENTO(PONTO_ID) ON DELETE CASCADE
);

CREATE TABLE GS_HISTORICO_CARREGAMENTO (
    HISTORICO_ID INT DEFAULT NEXT VALUE FOR GS_HISTORICO_CARREGAMENTO_SEQ PRIMARY KEY,
    USUARIO_ID INT NOT NULL,
    PONTO_ID INT NOT NULL,
    DATA_CARREGAMENTO DATETIME2 DEFAULT GETDATE(),
    ENERGIA_CONSUMIDA FLOAT,
    EMISSOES_EVITADAS FLOAT,
    CONSTRAINT FK_USUARIO_HISTORICO FOREIGN KEY (USUARIO_ID) REFERENCES GS_USUARIO(USUARIO_ID) ON DELETE CASCADE,
    CONSTRAINT FK_PONTO_HISTORICO FOREIGN KEY (PONTO_ID) REFERENCES GS_PONTO_CARREGAMENTO(PONTO_ID) ON DELETE CASCADE
);

CREATE TABLE GS_AVALIACAO (
    AVALIACAO_ID INT DEFAULT NEXT VALUE FOR GS_AVALIACAO_SEQ PRIMARY KEY,
    USUARIO_ID INT NOT NULL,
    POSTO_ID INT NOT NULL,
    NOTA INT CHECK (NOTA BETWEEN 1 AND 5),
    COMENTARIO VARCHAR(500),
    DATA_AVALIACAO DATETIME2 DEFAULT GETDATE(),
    CONSTRAINT FK_USUARIO_AVALIACAO FOREIGN KEY (USUARIO_ID) REFERENCES GS_USUARIO(USUARIO_ID) ON DELETE CASCADE,
    CONSTRAINT FK_POSTO_AVALIACAO FOREIGN KEY (POSTO_ID) REFERENCES GS_POSTO_CARREGAMENTO(POSTO_ID) ON DELETE CASCADE
);

CREATE TABLE GS_VIAGEM (
    VIAGEM_ID INT DEFAULT NEXT VALUE FOR GS_VIAGEM_SEQ PRIMARY KEY,
    USUARIO_ID INT NOT NULL,
    ORIGEM VARCHAR(50),
    DESTINO VARCHAR(50),
    AUTONOMIA_RESTANTE FLOAT,
    DATA_CRIACAO DATETIME2 DEFAULT GETDATE(),
    CONSTRAINT FK_USUARIO_VIAGEM FOREIGN KEY (USUARIO_ID) REFERENCES GS_USUARIO(USUARIO_ID) ON DELETE CASCADE
);

CREATE TABLE GS_PONTO_PARADA (
    PONTO_PARADA_ID INT DEFAULT NEXT VALUE FOR GS_PONTO_PARADA_SEQ PRIMARY KEY,
    VIAGEM_ID INT NOT NULL,
    PONTO_ID INT NOT NULL,
    ORDEM INT,
    CONSTRAINT FK_VIAGEM_PARADA FOREIGN KEY (VIAGEM_ID) REFERENCES GS_VIAGEM(VIAGEM_ID) ON DELETE CASCADE,
    CONSTRAINT FK_PONTO_PARADA FOREIGN KEY (PONTO_ID) REFERENCES GS_PONTO_CARREGAMENTO(PONTO_ID) ON DELETE CASCADE
);